# tracker/report.py

import os

def build_markdown_report(records):
    """
    Buat tabel rekap dalam format Markdown dari list records. [cite: 50]
    Format output disesuaikan dengan contoh di PDF. [cite: 96-103]
    """
    if not records:
        return "Tidak ada data untuk dilaporkan."
    
    # Urutkan berdasarkan NIM
    records.sort(key=lambda x: x['nim'])

    # Header
    header = [
        "# Rekap Nilai Mahasiswa",
        "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |",
        "|---|---|---|---:|:---:|"  # Sesuai alignment [cite: 98]
    ]
    
    # Rows
    rows = []
    for rec in records:
        # Format nilai: hadir 1 desimal, nilai akhir 2 desimal
        row = f"| {rec['nim']} | {rec['nama']} | {rec['hadir']:.1f} | {rec['nilai_akhir']:.2f} | {rec['predikat']} |"
        rows.append(row)
        
    # Footer
    footer = "\nGenerated by student_performance_tracker" # [cite: 103]
    
    content = header + rows + [footer]
    return "\n".join(content)

def save_text(path, content):
    """
    Simpan konten teks (string) ke sebuah file. [cite: 51]
    Akan membuat direktori 'out' jika belum ada.
    """
    # Pastikan direktori (misal 'out/') ada
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
            
    try:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"[bold green]Laporan berhasil disimpan ke {path}[/bold green]")
    except IOError as e:
        print(f"[bold red]Error: Gagal menyimpan file ke {path}. {e}[/bold red]")
    except Exception as e:
        print(f"[bold red]Error tidak terduga: {e}[/bold red]")
        
# tracker/report.py (TAMBAHKAN FUNGSI INI DI AKHIR FILE)

def build_html_report(records):
    """
    Buat laporan rekap dalam format HTML, dengan warna berdasarkan predikat.
    """
    if not records:
        return "<h1>Tidak ada data untuk dilaporkan.</h1>"

    # Urutkan berdasarkan NIM
    records.sort(key=lambda x: x['nim'])
    
    # Definisikan CSS untuk warna predikat
    html_css = """
<style>
    body { font-family: sans-serif; margin: 2em; }
    table { border-collapse: collapse; width: 80%; margin: auto; }
    th, td { border: 1px solid #ddd; padding: 8px; }
    th { background-color: #f2f2f2; }
    tr:nth-child(even) { background-color: #f9f9f9; }
    h1, footer { text-align: center; }
    
    /* Warna Predikat */
    .predikat-A { background-color: #e6ffed; }
    .predikat-B { background-color: #e6f7ff; }
    .predikat-C { background-color: #fffbeb; }
    .predikat-D { background-color: #fff0f0; }
    .predikat-E { background-color: #ffe6e6; font-weight: bold; color: #9c0000; }
</style>
"""
    
    # Header HTML
    html_content = [
        "<!DOCTYPE html>",
        "<html lang='id'>",
        "<head>",
        "<meta charset='UTF-8'>",
        "<title>Rekap Nilai Mahasiswa</title>",
        html_css,
        "</head>",
        "<body>",
        "<h1>Rekap Nilai Mahasiswa</h1>",
        "<table>",
        "<thead>",
        "<tr>",
        "<th>NIM</th>",
        "<th>Nama</th>",
        "<th>Hadir (%)</th>",
        "<th>Nilai Akhir</th>",
        "<th>Predikat</th>",
        "</tr>",
        "</thead>",
        "<tbody>"
    ]
    
    # Rows
    for rec in records:
        predikat = rec['predikat']
        row = f"<tr class='predikat-{predikat}'>"
        row += f"<td>{rec['nim']}</td>"
        row += f"<td>{rec['nama']}</td>"
        row += f"<td style='text-align:right;'>{rec['hadir']:.1f}</td>"
        row += f"<td style='text-align:right;'>{rec['nilai_akhir']:.2f}</td>"
        row += f"<td style='text-align:center;'>{predikat}</td>"
        row += "</tr>"
        html_content.append(row)

    # Footer HTML
    html_content.extend([
        "</tbody>",
        "</table>",
        "<footer><p>Generated by student_performance_tracker</p></footer>",
        "</body>",
        "</html>"
    ])
    
    return "\n".join(html_content)